
# /Users/bernapanarello/dbox/Dropbox/TLEN/tp2/repo/tleng-tp2/python/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'A4823B68843E32CF8E1DF0DB05C7DC14'
    
_lr_action_items = {'NUM':([0,],[1,]),'CNAME':([0,],[2,]),'$end':([1,2,3,],[-1,-2,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'value':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> value","S'",1,None,None,None),
  ('value -> NUM','value',1,'p_val_num','parser_rules.py',76),
  ('value -> CNAME','value',1,'p_val_cname','parser_rules.py',82),
  ('const -> CONST CNAME EQUALS NUM SEMICOLON','const',5,'p_const','parser_rules.py',86),
]
